### ISSUE TITLE
Unhide password

### ISSUE THREAD

**Issue by bananenfalter** [razmo/Razmo-MDM#4]
Hi, could you add a checkbox to unmask the password? May be it should be unmasked by default and only checking the checkbox should make it hidden. Something like this:

```html
<input name="password" type="text" tabindex="2" class="form-control span4" placeholder="Password"/>
…
<input name="pwcheck" type="checkbox" tabindex="3">Hide password</input>
```

```javascript
$('#login input[name=pwcheck]').bind("click", function(event){
	var isChecked = $('#login input[name=pwcheck]').is(':checked');
	$('#login input[name=password]').attr('type', isChecked ? 'password' : 'text');
});
```

Reason: 1. Typing errors can be corrected in a very simple way. 2. Users tend to chose very simple passwords, if they can’t see them.

See: 
Andrew Nielsen http://www.nngroup.com/articles/stop-password-masking/
Bruce Schneier https://www.schneier.com/blog/archives/2009/07/the_pros_and_co.html

I like your MDM greeter!
Bananenfalter

**Comment by razmo** [comment]
:+1: 
Good idea. Maybe something like this: http://cloudfour.github.io/hideShowPassword
I gonna do it as soon as i can.

**Comment by jamyouss** [comment]
Done !

**Comment by bananenfalter** [comment]
Only now I recognized that you did it. Pretty cool! :-)
May be a gray icon would match better with the other elements. They do have a Bootstrap glyphicon for this too: glyphicon glyphicon-eye-open and glyphicon glyphicon-eye-close
But that’s just an idea.
I like it!
